### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by vindarel** [levisabah/we-get#1]
To be notified when it's available :)

pretty work !

**Comment by 0xl3vi** [comment]
@vindarel just "watch" the project!
I will add it soon, and also archlinux AUR package.

**Comment by rachmadaniHaryono** [comment]
actually try install with `pip install git+https://github.com/0xl3vi/we-get` and it work

also maybe don't recommend `sudo pip install`. SO links:
- http://stackoverflow.com/questions/15028648/is-it-acceptable-safe-to-run-pip-install-under-sudo
- http://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice

**Comment by 0xl3vi** [comment]
Hi @rachmadaniHaryono I will not recommend `sudo pip install .`
I wil create package for pip when more modules will be added.

thank you :smile:
