### ISSUE TITLE
Pip package doesn't download useragents.txt file

### ISSUE THREAD

**Issue by aleksandar-todorovic** [levisabah/we-get#8]
* Platform: Ubuntu GNOME 17.04

### Description

Using `pip install we-get`, I haven't been able to execute `we-get`, since `~/.local.bin` is not in the `$PATH` by default. After adding the `alias we-get="/home/<USERNAME>/.local/bin/we-get"` to my `rc` file, I got to execute the `we-get` package, so I tried executing `we-get -G` to make sure that everything's working properly, and it seemed like it did.

However, executing some stupid command like:

    we-get --search "ghost in the shell" --target the_pirate_bay -n 10 -q 720

I get the following message:

    # error: Cannot open: /home/r3bl/.local/lib/python3.5/site-packages/we_get/txt/useragents.txt - to read user agents.

Upon further inspection, there's indeed no `txt` directory there nor the `useragents.txt` file in that directory. Easily solvable by creating the file and populating it with the content from this repo, but not really a seamless experience out-of-the-box.

**Comment by levisabah** [comment]
Hi @aleksandar-todorovic thanks!
I will try to fix it now.

**Comment by levisabah** [comment]
@aleksandar-todorovic can you verify?

**Comment by levisabah** [comment]
use `sudo` to avoid setting the $PATH, it will install we-get globally.

**Comment by aleksandar-todorovic** [comment]
I can verify that the commit fixed the issue.

As for the $PATH, a small note in the README (since the default instruction don't use `sudo`) to add the directory to $PATH would be more than enough in my opinion.
